### PR TITLE
Stax/flex support

### PR DESCRIPTION
**Pull request by steel97**
- split code to use nbgl for flex/stax, bagl for nanos+/nanox
- removed nanos target

# Checklist

- [ ] App update process has been followed 
- [ ] Target branch is `develop` 
- [x] Application version has been bumped

### CODE REVIEW

**Review by arobsn — CHANGES_REQUESTED** [review]
* Left a small suggestion on `CHANGELOG.md`
* There is one CI job failing, can you please check?
* Additionally, can you please set `TOKEN_MAX_COUNT` to `100`? This will fix #18. From my tests `250+` tokens are possible, but `100` is a reasonable number and gives us room for further changes.
* I will do functional tests on my tomorrow and drop my comments here once it's finished

**Comment by steel97** [comment]
> * Left a small suggestion on `CHANGELOG.md`
> 
Done
> * There is one CI job failing, can you please check?
> 
screenshot
According to log, we should open PR in https://github.com/LedgerHQ/ledger-app-database
Flex and Stax should be added here:
https://github.com/LedgerHQ/ledger-app-database/blob/9357fa1f895d40989757e4c78dd1173f672a481d/app-load-params-db.json#L990
If I'am not wrong it should look like:
```
"appFlags": {"nanos": "0x000", "nanos2": "0x000", "nanox": "0x200", "stax": "0x200", "flex": "0x200"},
```
> * Additionally, can you please set `TOKEN_MAX_COUNT` to `100`? This will fix [Increase `TOKEN_MAX_COUNT` #18](https://github.com/ergoplatform/ledger-app-ergo/issues/18). From my tests `250+` tokens are possible, but `100` is a reasonable number and gives us room for further changes.
> 
Done
> * I will do functional tests on my tomorrow and drop my comments here once it's finished

**Comment by arobsn** [comment]
Great! Thanks for your quick response. I believe @kushti forwarded you an additional review from another developer.


> According to log, we should open PR in https://github.com/LedgerHQ/ledger-app-database

Done, https://github.com/LedgerHQ/ledger-app-database/pull/269

**Review by arobsn — CHANGES_REQUESTED** [review]
Found some issues while doing functional tests.

## Derive address operation
* It should be a one screen operation, just like in "Ext PubKey Export command".
* Currently it displays "Confirm send address", it would be good to keep it consistent with other "export" commands, so please rename it to "Address Export".

## Sign operation
* It's showing a zeroed AppID page even if no `AppId` is send.
Screenshot 2024-10-17 at 17 37 50

Please note that this review isn't definitive, just wanted to report what I have ASAP so you can have something to work with, I'm still working on functional tests and new issues can eventually come up

**Comment by arobsn** [comment]
Found more issues on the Tx Signing flow:

1. The user is not able to navigate back on the signing screens, just forward.
2. Transaction signing crashes when the user clicks "confirm", with no error code, just a blank screen. Here you can see an minimal reproduction of the issue: https://github.com/arobsn/ledger-issue-minimal-reproduction

**Comment by steel97** [comment]
>     * It should be a one screen operation, just like in "Ext PubKey Export" command.
> 
Done
>     * Currently it displays "Confirm send address", it would be good to keep it consistent with other "export" commands, so please rename it to "Address Export".
> 
Done
> 
> ## Sign operation
> 
>     * It's showing a zeroed AppID page even if no `AppId` is send.
> 
Should be fixed with last commits

**Comment by steel97** [comment]
>     2. Transaction signing crashes when the user clicks "confirm", with no error code, just a blank screen. Here you can see an minimal reproduction of the issue: https://github.com/arobsn/ledger-issue-minimal-reproduction
>        **Edit**: Just confirmed that the `minimal-reproduction` code works perfectly on the `nanosp` build

Confirm is shown on `Attest input` stage, do you mean `Approve signing` stage?
image
For some reason it works for me in both debug/release builds.
Could you please try latest version?
image

**Comment by steel97** [comment]
>
>     1. The user is not able to navigate back on the signing screens, just forward.
> 
I made few improvements. Now back button is active in certain cases (should match nano x/s+ behavior).
Basically it's possible to navigate forward/backward while reviewing tokens.

image

**Comment by steel97** [comment]
@arobsn actually I noticed that 0x00000000 app id is also shown in nano s+ build when signing tx:
image

**Review by arobsn — CHANGES_REQUESTED** [review]
## Address derivation
* On both "Address export" and "Address confirm", `change` and `index` nodes of the derivation path are getting omitted. If I request `44'/429'/0'/0/0`, only `44'/429'/0` is displayed, for example.

# Transaction signing
I can confirm that signing is not crashing as previously reported, it was a mistake on my side, I though that just clicking on "hold to sign" was enough, but I need to click-and-hold until signing process is finished, not sure if it's a VNC issue tho.

* Change must be displayed in the outputs confirm flow if `CHANGE_INDEX_PATH - SIGN_INDEX_PATH > 19`, this is important to avoid bad agents to set change to something like `change_index = Int.MAX`, see details in "Change confirmations" in #11

**Comment by arobsn** [comment]
> @arobsn actually I noticed that 0x00000000 app id is also shown in nano s+ build when signing tx:

Thank you

**Review by arobsn — APPROVED** [review]
Everything seems to be working as expected now. Thanks

**Pull request merged**
